Import libraries

In [1]:
import pandas as pd
from ks import ks

Read made-up data

In [2]:
df = pd.read_csv('ks_example.csv', dtype={'target':'int'})
df.head()

   target  negative_relationship_score  positive_relationship_score
0       1                     0.649606                     0.350394
1       0                     0.700787                     0.299213
2       1                     0.795276                     0.204724
3       1                     0.468504                     0.531496
4       0                     0.641732                     0.358268

# Case 1

The relationship between score and target is negative (*the greater the score, the lower the lower expected probability of event*)

In [3]:
t = ks(score=df['negative_relationship_score'], target=df['target'], bins=20, negative_relationship=True,
       round_intervals=False, print_table=False, write_table=False)
t

KS: 0.16 out of 1.00

,bin,count,bads,goods,bad_rate_in_bin,cumulative_bad_rate,cumulative_good_rate,ks,remaining_bad_rate
0,"(0.0974, 0.445]",254,96,158,0.377953,0.081633,0.041318,0.040315,0.235200
1,"(0.445, 0.504]",262,91,171,0.347328,0.159014,0.086036,0.072978,0.227560
2,"(0.504, 0.539]",257,87,170,0.338521,0.232993,0.130492,0.102502,0.220562
3,"(0.539, 0.567]",255,86,169,0.337255,0.306122,0.174686,0.131436,0.213390
4,"(0.567, 0.587]",260,72,188,0.276923,0.367347,0.223849,0.143498,0.205438
5,"(0.587, 0.602]",248,71,177,0.286290,0.427721,0.270136,0.157585,0.200431
6,"(0.602, 0.614]",244,62,182,0.254098,0.480442,0.317730,0.162712,0.194284
7,"(0.614, 0.626]",249,57,192,0.228916,0.528912,0.367939,0.160972,0.189752
8,"(0.626, 0.642]",279,64,215,0.229391,0.583333,0.424163,0.159170,0.186469
9,"(0.642, 0.654]",270,65,205,0.240741,0.638605,0.477772,0.160833,0.182021
10,"(0.654, 0.661]",200,49,151,0.245000,0.680272,0.517259,0.163013,0.175475
11,"(0.661, 0.677]",342,60,282,0.175439,0.731293,0.591004,0.140288,0.169217
12,"(0.677, 0.685]",216,40,176,0.185185,0.765306,0.637029,0.128277,0.168085
13,"(0.685, 0.697]",250,47,203,0.188000,0.805272,0.690115,0.115157,0.165865
14,"(0.697, 0.705]",165,35,130,0.212121,0.835034,0.724111,0.110923,0.161952
15,"(0.705, 0.72]",286,55,231,0.192308,0.881803,0.784519,0.097284,0.155324
16,"(0.72, 0.736]",263,37,226,0.140684,0.913265,0.843619,0.069646,0.144341
17,"(0.736, 0.756]",245,37,208,0.151020,0.944728,0.898013,0.046715,0.145714
18,"(0.756, 0.783]",217,37,180,0.170507,0.976190,0.945084,0.031107,0.142857
19,"(0.783, 0.969]",238,28,210,0.117647,1.000000,1.000000,0.000000,0.117647

# Case 2:

The relationship between score and target is positive (*the greater the score, the higher the expected probability*)
Cuando la relación entre score y target es positiva (a mayor score, mayor riesgo)

In [4]:
ks(score=df['positive_relationship_score'], target=df['target'], bins=10, negative_relationship=False,
   round_intervals=False, print_table=False, write_table=False)

KS: 0.16 out of 1.00

,bin,count,bads,goods,bad_rate_in_bin,cumulative_bad_rate,cumulative_good_rate,ks,remaining_bad_rate
0,"(0.0305, 0.244]",524,77,447,0.146947,1.000000,1.000000,0.000000,0.146947
1,"(0.244, 0.28]",505,71,434,0.140594,0.934524,0.883107,0.051417,0.143829
2,"(0.28, 0.303]",476,101,375,0.212185,0.874150,0.769613,0.104537,0.165449
3,"(0.303, 0.323]",506,85,421,0.167984,0.788265,0.671548,0.116717,0.166087
4,"(0.323, 0.346]",522,117,405,0.224138,0.715986,0.561454,0.154532,0.178050
5,"(0.346, 0.374]",531,126,405,0.237288,0.616497,0.455544,0.160953,0.188316
6,"(0.374, 0.398]",463,112,351,0.241901,0.509354,0.349634,0.159720,0.195350
7,"(0.398, 0.433]",483,135,348,0.279503,0.414116,0.257845,0.156270,0.205486
8,"(0.433, 0.496]",498,168,330,0.337349,0.299320,0.166841,0.132479,0.220053
9,"(0.496, 0.902]",492,184,308,0.373984,0.156463,0.080544,0.075919,0.235200